package com.cayzlh.jwt.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * Table:
 *   t_auth_role
 *
 * @author Ant丶
 * @mbg.generated
 */
public class AuthRole implements Serializable {
    /**
     * Description:
     *   主键
     *
     * Column:
     *   t_auth_role.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Description:
     *   用户名
     *
     * Column:
     *   t_auth_role.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Description:
     *   角色
     *
     * Column:
     *   t_auth_role.authority
     *
     * @mbg.generated
     */
    private String authority;

    /**
     * Description:
     *   创建时间
     *
     * Column:
     *   t_auth_role.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Description:
     *  This field corresponds to the database table t_auth_role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Description:
     *  This field corresponds to the database table t_auth_role
     *
     * @mbg.generated
     */
    private Map<String, Boolean> selectiveColumns = new HashMap<String, Boolean>();

    /**
     * Description:
     *  返回 t_auth_role.id 的值
     *
     * @return 字段 t_auth_role.id 的值
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * Description:
     *  设置 t_auth_role.id 的值.
     *
     * @param id 字段 t_auth_role.id 的值.
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Description:
     *  返回 t_auth_role.user_name 的值
     *
     * @return 字段 t_auth_role.user_name 的值
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Description:
     *  设置 t_auth_role.user_name 的值.
     *
     * @param userName 字段 t_auth_role.user_name 的值.
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * Description:
     *  返回 t_auth_role.authority 的值
     *
     * @return 字段 t_auth_role.authority 的值
     *
     * @mbg.generated
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * Description:
     *  设置 t_auth_role.authority 的值.
     *
     * @param authority 字段 t_auth_role.authority 的值.
     *
     * @mbg.generated
     */
    public void setAuthority(String authority) {
        this.authority = authority == null ? null : authority.trim();
    }

    /**
     * Description:
     *  返回 t_auth_role.create_time 的值
     *
     * @return 字段 t_auth_role.create_time 的值
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * Description:
     *  设置 t_auth_role.create_time 的值.
     *
     * @param createTime 字段 t_auth_role.create_time 的值.
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * Description: This method was generated by MyBatis Generator.
     *
     * @return toString 的结果.
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", authority=").append(authority);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Description: This method was generated by MyBatis Generator.
     *
     * @return builder 的结果.
     * @mbg.generated
     */
    public static AuthRole.Builder builder() {
        return new AuthRole.Builder();
    }

    /**
     * Description: This method was generated by MyBatis Generator.
     *
     * @return hasSelective 的结果.
     * @mbg.generated
     */
    public boolean hasSelective() {
        return this.selectiveColumns.size() > 0;
    }

    /**
     * Description: This method was generated by MyBatis Generator.
     *
     * @return hasSelective 的结果.
     * @mbg.generated
     */
    public boolean hasSelective(String column) {
        return this.selectiveColumns.get(column) != null;
    }

    /**
     * Description: This method was generated by MyBatis Generator.
     *
     * @return selective 的结果.
     * @mbg.generated
     */
    public AuthRole selective(Column ... columns) {
        this.selectiveColumns.clear();
        if (columns != null) {
            for (Column column : columns) {
                this.selectiveColumns.put(column.value(), true);
            }
        }
        return this;
    }

    /**
     * Description:
     *  This class corresponds to the database table t_auth_role
     *
     * @author Ant丶
     * @mbg.generated
     */
    public static class Builder {
        /**
         * Description:
         *  This field corresponds to the database table t_auth_role
         *
         * @mbg.generated
         */
        private AuthRole obj;

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return Builder 的结果.
         * @mbg.generated
         */
        public Builder() {
            this.obj = new AuthRole();
        }

        /**
         * Description:
         *  设置 t_auth_role.id 的值.
         *
         * @param id 字段 t_auth_role.id 的值.
         *
         * @mbg.generated
         */
        public Builder id(Long id) {
            obj.setId(id);
            return this;
        }

        /**
         * Description:
         *  设置 t_auth_role.user_name 的值.
         *
         * @param userName 字段 t_auth_role.user_name 的值.
         *
         * @mbg.generated
         */
        public Builder userName(String userName) {
            obj.setUserName(userName);
            return this;
        }

        /**
         * Description:
         *  设置 t_auth_role.authority 的值.
         *
         * @param authority 字段 t_auth_role.authority 的值.
         *
         * @mbg.generated
         */
        public Builder authority(String authority) {
            obj.setAuthority(authority);
            return this;
        }

        /**
         * Description:
         *  设置 t_auth_role.create_time 的值.
         *
         * @param createTime 字段 t_auth_role.create_time 的值.
         *
         * @mbg.generated
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return build 的结果.
         * @mbg.generated
         */
        public AuthRole build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_auth_role
     *
     * @mbg.generated
     */
    public enum Column {
        id("id"),
        userName("user_name"),
        authority("authority"),
        createTime("create_time");

        /**
         * Description:
         *  This field corresponds to the database table t_auth_role
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return value 的结果.
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return getValue 的结果.
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @param  column column
         * @return Column 的结果.
         * @mbg.generated
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return desc 的结果.
         * @mbg.generated
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return asc 的结果.
         * @mbg.generated
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}